# Generated by Django 4.0.6 on 2022-07-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_heart_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
    ]
