# Generated by Django 4.0.6 on 2022-07-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_devtool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devtool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_devtool', to='posts.devtool'),
        ),
    ]
